name: Build and Push Docker image

on:
  push:
    branches: [main]

env:
  APP_NAME: myapp
  VERSION: 1.0.0
  REGISTRY_NAME: marcosfreitas.azurecr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: SECRETS

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_NAME }}
        username: ${{ secrets.AZURE_ACR_USERNAME }}
        password: ${{ secrets.AZURE_ACR_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -f my-app/Dockerfile -t ${{ env.REGISTRY_NAME }}/${{ env.APP_NAME }}:${{ env.VERSION }} my-app
        docker tag ${{ env.REGISTRY_NAME }}/${{ env.APP_NAME }}:${{ env.VERSION }} ${{ env.REGISTRY_NAME }}/${{ env.APP_NAME }}:latest

    - name: Push Docker image
      run: |
        docker push ${{ env.REGISTRY_NAME }}/${{ env.APP_NAME }}:${{ env.VERSION }}
        docker push ${{ env.REGISTRY_NAME }}/${{ env.APP_NAME }}:latest
